# Site settings
title: Antoncabon
email: antoncabon77@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just personal blog on github.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://antoncabon.github.io" # the base hostname & protocol for your site
twitter_username: antoncabon
github_username:  antoncabon

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Learn
    url: /learn
  - title: Sitemap
    url: /daftar-isi
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: Resume
    url: /cv

collections:
  - cursos

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
